apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-arbiter-manager-rolebinding
  labels:
    app.kubernetes.io/name: gpu-arbiter-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: gpu-arbiter-controller-manager
    namespace: gpu-arbiter-system
