//go:build !ignore_autogenerated

// Copyright 2026 biggs.dog.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUArbiter) DeepCopyInto(out *GPUArbiter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUArbiter.
func (in *GPUArbiter) DeepCopy() *GPUArbiter {
	if in == nil {
		return nil
	}
	out := new(GPUArbiter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUArbiter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUArbiterList) DeepCopyInto(out *GPUArbiterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUArbiter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUArbiterList.
func (in *GPUArbiterList) DeepCopy() *GPUArbiterList {
	if in == nil {
		return nil
	}
	out := new(GPUArbiterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUArbiterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUArbiterSpec) DeepCopyInto(out *GPUArbiterSpec) {
	*out = *in
	out.VLLM = in.VLLM
	in.Game.DeepCopyInto(&out.Game)
	out.Metrics = in.Metrics
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUArbiterSpec.
func (in *GPUArbiterSpec) DeepCopy() *GPUArbiterSpec {
	if in == nil {
		return nil
	}
	out := new(GPUArbiterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUArbiterStatus) DeepCopyInto(out *GPUArbiterStatus) {
	*out = *in
	if in.CurrentVLLMReplicas != nil {
		in, out := &in.CurrentVLLMReplicas, &out.CurrentVLLMReplicas
		*out = new(int32)
		**out = **in
	}
	if in.DesiredVLLMReplicas != nil {
		in, out := &in.DesiredVLLMReplicas, &out.DesiredVLLMReplicas
		*out = new(int32)
		**out = **in
	}
	if in.FreeVRAMMiB != nil {
		in, out := &in.FreeVRAMMiB, &out.FreeVRAMMiB
		*out = new(int64)
		**out = **in
	}
	if in.GatedPods != nil {
		in, out := &in.GatedPods, &out.GatedPods
		*out = make([]GatedPodStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastReconcile.DeepCopyInto(&out.LastReconcile)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUArbiterStatus.
func (in *GPUArbiterStatus) DeepCopy() *GPUArbiterStatus {
	if in == nil {
		return nil
	}
	out := new(GPUArbiterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameTarget) DeepCopyInto(out *GameTarget) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameTarget.
func (in *GameTarget) DeepCopy() *GameTarget {
	if in == nil {
		return nil
	}
	out := new(GameTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatedPodStatus) DeepCopyInto(out *GatedPodStatus) {
	*out = *in
	in.FirstSeen.DeepCopyInto(&out.FirstSeen)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatedPodStatus.
func (in *GatedPodStatus) DeepCopy() *GatedPodStatus {
	if in == nil {
		return nil
	}
	out := new(GatedPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSource) DeepCopyInto(out *MetricsSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSource.
func (in *MetricsSource) DeepCopy() *MetricsSource {
	if in == nil {
		return nil
	}
	out := new(MetricsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMTarget) DeepCopyInto(out *VLLMTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMTarget.
func (in *VLLMTarget) DeepCopy() *VLLMTarget {
	if in == nil {
		return nil
	}
	out := new(VLLMTarget)
	in.DeepCopyInto(out)
	return out
}
